#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/green_dots"

$LOAD_PATH.unshift File.expand_path("fixtures")

Dir.glob("test/support/**/*.rb").each { |f| eval File.read(f), binding, f, 1 }

Dir.glob("test/**/*.rb").reject { |f| f.start_with? "test/support/" }.shuffle.each do |f|
	Class.new(GreenDots::Test) do
		class_eval(
			File.read(f), f, 1
		)
	end.run
end

puts
puts
puts "Success! ✅"
puts "All your tests passed. 💃"
