#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/green_dots"

require "etc"

GreenDots.run(
	number_of_processes: Etc.nprocessors,
	directory: ARGV[0] || "test",
	test_files: Dir.glob("./**/*.test.rb").reject { |f| f.start_with? "#{@directory}/support/" }
)
